### ISSUE TITLE
关于通过kvc设置成员变量值的问题

### ISSUE THREAD

**Issue by SimonCY** [ParsifalC/NetEaseBaymaxDemo#5]
通过kvc设置成员变量值时，也会触发消息转发机制，目前demo中有这部分相关的处理吗？

**Comment by ParsifalC** [comment]
KVC 设置成员变量值会触发消息转发机制，这个据我了解应该是没有的。

但是 KVO 中非 Core Foundation 类型监听，确实会触发转发逻辑。demo 里只做了 `forwardInvocation:` 是否被复写的判断，可以再加上 `forwardingTargetForSelector:` 的判断。

demo 只是为了方案预演而随意写的一些测试，很多细节并没有去做，不可直接用于正式工程。

@SimonCY

**Comment by SimonCY** [comment]
嗯      感谢
